### PR TITLE
Version 1.0.1: Python 3.5, Juniper compatibility

### LINKED ISSUE #8: Tripped up by not using caching
In lms_api.py, the object will always set an attribute _cache_.  It might be bool, or it might point to the cached information if in settings.py LMS_API_USE_MEMCACHED is true.

However, later, when deciding whether to scan cache or re-query xAPI, the test is simply 
`if hasattr(self, 'cache'):`

This will always be true.  And because of that, later in the block if one is not using caching
`cached_user_info = self.cache.get(self.CACHE_ACCOUNTS_PREFIX + username)`

Will result in the following error:
"bool' object has no attribute 'set'"

A simple fix was:
`if hasattr(self, 'cache') and not isinstance(self.cache,bool):`

However, it would be more logical to either have:
- have 2 properties - one that says there's caching and the other one pointing to such, or
- not create the "cache" attribute in the first place if there's no need

### PR DESCRIPTION
**Pull request by bryanlandia**
## Change description

Get it working with Python 3 (dropped Py2.7 support)
Fix a few small issues

https://appsembler.atlassian.net/browse/BLACK-1874

## Type of change
- [x] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

Fixes #8 

### Development

- [x] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [x] Automated tests covering modified code pass

### Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### Code review 

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [x] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [x] Pull request linked to task tracker where applicable

### CODE REVIEW

**Comment by bryanlandia** [comment]
@johnbaldwin including you as an FYI

File: xapi_bridge/__init__.py [hunk 1]
```diff
@@ -1 +1 @@
-__version__ = "0.1"
+__version__ = "1.0.1"
```
Comment (johnbaldwin) [inline xapi_bridge/__init__.py:1]: I don't see any existing releases. Reason to skip 1.0.0?

File: xapi_bridge/exceptions.py [hunk 2]
```diff
@@ -32,7 +32,7 @@ def update_sentry_scope(self, scope, level='warning', user=None, **kwargs):
         if user:
             scope.user = {"username": user}  # TODO: get email if possible
         if kwargs:
-            for key, value in kwargs.iteritems():
+            for key, value in list(kwargs.items()):
```
Comment (johnbaldwin) [inline xapi_bridge/exceptions.py:35]: Why create a list instead of just `for key, value in kwargs.items():` ?

File: xapi_bridge/statements/problem.py [hunk 3]
```diff
@@ -52,7 +51,7 @@ def get_result(self, event):
         event_data = self.get_event_data(event)
         # for now we are going to assume one submission
         # TODO: when is that not true? is it ever not true? What problem types?
-        submission = event_data['submission'][event_data['submission'].keys()[0]]
+        submission = event_data['submission'][list(event_data['submission'].keys())[0]]
```
Comment (johnbaldwin) [inline xapi_bridge/statements/problem.py:54]: I strongly suggest this raises an error for multiple keys. If that is simply unpalatable, then definitely logging this if there is more than one key in `event_data['sugmission']`?
I'm not familiar at all with the `xapi_bridge` package, but in general it seems if there do happen to be multiple keys and the wrong key is used, what's the downside? Silent bad data?

**Review by johnbaldwin — APPROVED** [review]
@bryanlandia Approving, but please see my comment on the submission assignment from event_data in the `ProblemStatement~ class. I strongly urge handling of the event of multiple keys if this results in a silent failure or fixing the data on discovery is messy or expensive. There might be other places in this code too that grab the first element of dict keys. I haven't checked

File: xapi_bridge/exceptions.py (hunk 2 above)
Comment (thraxil) [reply xapi_bridge/exceptions.py:35]: @johnbaldwin this appears to be an automatic conversion done by `2to3`.

**Comment by thraxil** [comment]
Anything still holding this one up?
